#
# Makefile for rogue
# @(#)Makefile	4.21 (Berkeley) 02/04/99
#
# Rogue: Exploring the Dungeons of Doom
# Copyright (C) 1980-1983, 1985, 1999 Michael Toy, Ken Arnold and Glenn Wichman
# All rights reserved.
#
# See the file LICENSE.TXT for full copyright and licensing information.
#

DISTNAME = rogue5.4.4
PROGRAM  = rogue54
O        = o
HDRS     = rogue.h extern.h score.h tiles.h tilepack.h rogue_platform.h frontend.h overlay_picker.h \
           mobile_controls.h \
           variant.h \
           generated/rogue_tile_mapping.h
ALLEGRO_OBJS =
ROGUE52_DIR = variants/rogue52
ROGUE52_BUILD = variants/rogue52/build
ROGUE52_CFILES = vers.c extern.c armor.c chase.c command.c daemon.c \
	   daemons.c fight.c init.c io.c list.c main.c mach_dep.c misc.c \
	   monsters.c move.c new_level.c options.c pack.c passages.c \
	   potions.c rings.c rip.c rooms.c save.c scrolls.c state.c \
	   sticks.c things.c weapons.c wizard.c xcrypt.c rogue52_port.c
ROGUE52_OBJS = $(ROGUE52_CFILES:%.c=$(ROGUE52_BUILD)/%.o)
ROGUE52_REDEF = $(ROGUE52_DIR)/rogue52_symbols.redef
ROGUE52_REDEF_EXPANDED = $(ROGUE52_BUILD)/rogue52_symbols.expanded.redef
ROGUE36_DIR = variants/rogue36
ROGUE36_BUILD = variants/rogue36/build
ROGUE36_CFILES = vers.c armor.c chase.c command.c daemon.c \
	   daemons.c fight.c init.c io.c list.c main.c misc.c \
	   monsters.c move.c newlevel.c options.c pack.c passages.c \
	   potions.c rings.c rip.c rooms.c save.c scrolls.c state.c \
	   sticks.c things.c weapons.c wizard.c xcrypt.c rogue36_port.c
ROGUE36_OBJS = $(ROGUE36_CFILES:%.c=$(ROGUE36_BUILD)/%.o)
ROGUE36_REDEF = $(ROGUE36_DIR)/rogue36_symbols.redef
ROGUE36_REDEF_EXPANDED = $(ROGUE36_BUILD)/rogue36_symbols.expanded.redef
ROGUE36_REFSECTIONS = $(ROGUE36_BUILD)/rogue36_refptr_sections.args
SROGUE90_DIR = variants/srogue90
SROGUE90_BUILD = variants/srogue90/build
SROGUE90_CFILES = vers.c armor.c chase.c command.c daemon.c daemons.c disply.c \
	   encumb.c fight.c global.c init.c io.c list.c main.c misc.c \
	   monsters.c move.c new_leve.c options.c pack.c passages.c \
	   potions.c pstats.c rings.c rip.c rooms.c save.c scrolls.c \
	   state.c sticks.c things.c trader.c weapons.c wizard.c xcrypt.c \
	   srogue90_port.c
SROGUE90_OBJS = $(SROGUE90_CFILES:%.c=$(SROGUE90_BUILD)/%.o)
SROGUE90_REDEF = $(SROGUE90_DIR)/srogue90_symbols.redef
SROGUE90_REDEF_EXPANDED = $(SROGUE90_BUILD)/srogue90_symbols.expanded.redef
SROGUE90_REFSECTIONS = $(SROGUE90_BUILD)/srogue90_refptr_sections.args
OBJS1    = vers.$(O) extern.$(O) armor.$(O) chase.$(O) command.$(O) \
           daemon.$(O) daemons.$(O) fight.$(O) init.$(O) io.$(O) list.$(O) \
	   mach_dep.$(O) main.$(O) mdport.$(O) misc.$(O) monsters.$(O) \
	   move.$(O) new_level.$(O)
OBJS2    = options.$(O) pack.$(O) passages.$(O) potions.$(O) rings.$(O) \
           rip.$(O) rooms.$(O) save.$(O) scrolls.$(O) state.$(O) sticks.$(O) \
	   things.$(O) tiles.$(O) tilepack.$(O) rogue_platform.$(O) frontend.$(O) overlay_picker.$(O) \
	   mobile_controls.$(O) \
	   variant.$(O) \
	   generated/rogue_tile_mapping.$(O) \
	   $(ALLEGRO_OBJS) weapons.$(O) \
	   wizard.$(O) xcrypt.$(O) $(ROGUE52_OBJS) $(ROGUE36_OBJS) \
	   $(SROGUE90_OBJS)
OBJS     = $(OBJS1) $(OBJS2)
CFILES   = vers.c extern.c armor.c chase.c command.c daemon.c \
	   daemons.c fight.c init.c io.c list.c mach_dep.c \
	   main.c  mdport.c misc.c monsters.c move.c new_level.c \
	   options.c pack.c passages.c potions.c rings.c rip.c \
	   rooms.c save.c scrolls.c state.c sticks.c things.c tiles.c tilepack.c rogue_platform.c \
	   frontend.c overlay_picker.c mobile_controls.c variant.c generated/rogue_tile_mapping.c \
	   allegro_frontend.c weapons.c wizard.c xcrypt.c
MISC_C   = findpw.c scedit.c scmisc.c
DOCSRC   = rogue.me.in rogue.6.in rogue.doc.in rogue.html.in rogue.cat.in
DOCS     = $(PROGRAM).doc $(PROGRAM).html $(PROGRAM).cat $(PROGRAM).me \
           $(PROGRAM).6
AFILES   = configure Makefile.in configure.ac config.h.in config.sub config.guess \
           install-sh rogue.6.in rogue.me.in rogue.html.in rogue.doc.in rogue.cat.in
MISC     = Makefile.std LICENSE.TXT rogue54.sln rogue54.vcproj rogue.spec \
           rogue.png rogue.desktop
CC       = gcc
OBJCOPY  = objcopy
FEATURES = -DALLSCORES -DSCOREFILE=\"$(SCOREFILE)\" -DLOCKFILE=\"$(LOCKFILE)\"
CPPFLAGS =
CFLAGS   = -O3
LDFLAGS  =
LIBS     = -lcurses
RM       = rm -f
MAKEFILE = -f Makefile.std
SCOREFILE= $(PROGRAM).scr
LOCKFILE = $(PROGRAM).lck
OUTFLAG  = -o
EXE      =

all: $(PROGRAM)

.SUFFIXES: .obj

.c.obj:
	$(CC) $(CFLAGS) $(CPPFLAGS) $(FEATURES) /c $*.c
    
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) $(FEATURES) -c $*.c

generated/rogue_tile_mapping.o: generated/rogue_tile_mapping.c generated/rogue_tile_mapping.h
	$(CC) $(CFLAGS) $(CPPFLAGS) $(FEATURES) -c generated/rogue_tile_mapping.c -o generated/rogue_tile_mapping.o

$(ROGUE52_REDEF_EXPANDED): $(ROGUE52_REDEF)
	mkdir -p $(ROGUE52_BUILD)
	awk '{ print; if ($$1 != "" && $$1 !~ /^\\./) print ".refptr." $$1 " rogue52_refptr_" $$1 }' $(ROGUE52_REDEF) > $@

$(ROGUE52_BUILD)/%.o: $(ROGUE52_DIR)/%.c $(ROGUE52_REDEF_EXPANDED) $(ROGUE52_DIR)/rogue52_port.h $(ROGUE52_DIR)/port/pwd.h $(ROGUE52_DIR)/port/termios.h
	mkdir -p $(ROGUE52_BUILD)
	$(CC) $(CFLAGS) -fcommon -I$(ROGUE52_DIR)/port -I$(ROGUE52_DIR) $(CPPFLAGS) -include $(ROGUE52_DIR)/rogue52_port.h -DSCOREFILE=\"rogue52.scr\" -DLOCKFILE=\"rogue52.lck\" -c $(ROGUE52_DIR)/$*.c -o $@
	$(OBJCOPY) --redefine-syms $(ROGUE52_REDEF_EXPANDED) $@

$(ROGUE36_REDEF_EXPANDED): $(ROGUE36_REDEF)
	mkdir -p $(ROGUE36_BUILD)
	awk '{ print; if ($$1 != "" && $$1 !~ /^\\./) { print ".refptr." $$1 " rogue36_refptr_" $$1; print ".rdata$$.refptr." $$1 " .rdata$$.refptr.rogue36_" $$1 } }' $(ROGUE36_REDEF) > $@

$(ROGUE36_REFSECTIONS): $(ROGUE36_REDEF)
	mkdir -p $(ROGUE36_BUILD)
	awk '{ if ($$1 != "" && $$1 !~ /^\\./) print "--rename-section .rdata$$.refptr." $$1 "=.rdata$$.refptr.rogue36_" $$1 }' $(ROGUE36_REDEF) > $@

$(ROGUE36_BUILD)/%.o: $(ROGUE36_DIR)/%.c $(ROGUE36_REDEF_EXPANDED) $(ROGUE36_REFSECTIONS) $(ROGUE36_DIR)/rogue36_port.h $(ROGUE36_DIR)/port/pwd.h $(ROGUE36_DIR)/port/termios.h
	mkdir -p $(ROGUE36_BUILD)
	$(CC) $(CFLAGS) -fcommon -I$(ROGUE36_DIR)/port -I$(ROGUE36_DIR) $(CPPFLAGS) -include $(ROGUE36_DIR)/rogue36_port.h -DSCOREFILE=\"rogue36.scr\" -DLOCKFILE=\"rogue36.lck\" -c $(ROGUE36_DIR)/$*.c -o $@
	$(OBJCOPY) --no-change-warnings --redefine-syms $(ROGUE36_REDEF_EXPANDED) @$(ROGUE36_REFSECTIONS) $@

$(SROGUE90_REDEF_EXPANDED): $(SROGUE90_REDEF)
	mkdir -p $(SROGUE90_BUILD)
	awk '{ print; if ($$1 != "" && $$1 !~ /^\\./) { print ".refptr." $$1 " srogue90_refptr_" $$1; print ".rdata$$.refptr." $$1 " .rdata$$.refptr.srogue90_" $$1 } }' $(SROGUE90_REDEF) > $@

$(SROGUE90_REFSECTIONS): $(SROGUE90_REDEF)
	mkdir -p $(SROGUE90_BUILD)
	awk '{ if ($$1 != "" && $$1 !~ /^\\./) print "--rename-section .rdata$$.refptr." $$1 "=.rdata$$.refptr.srogue90_" $$1 }' $(SROGUE90_REDEF) > $@

$(SROGUE90_BUILD)/%.o: $(SROGUE90_DIR)/%.c $(SROGUE90_REDEF_EXPANDED) $(SROGUE90_REFSECTIONS) $(SROGUE90_DIR)/srogue90_port.h $(SROGUE90_DIR)/port/pwd.h $(SROGUE90_DIR)/port/termios.h $(SROGUE90_DIR)/rogue.ext
	mkdir -p $(SROGUE90_BUILD)
	$(CC) $(CFLAGS) -fcommon -I$(SROGUE90_DIR)/port -I$(SROGUE90_DIR) $(CPPFLAGS) -include $(SROGUE90_DIR)/srogue90_port.h -DSCOREFILE=\"srogue90.scr\" -DLOCKFILE=\"srogue90.lck\" -c $(SROGUE90_DIR)/$*.c -o $@
	$(OBJCOPY) --no-change-warnings --redefine-syms $(SROGUE90_REDEF_EXPANDED) @$(SROGUE90_REFSECTIONS) $@
    
$(PROGRAM): $(HDRS) $(OBJS) fixdocs
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) $(OUTFLAG)$@$(EXE)
 
clean:
	$(RM) $(OBJS1)
	$(RM) $(OBJS2)
	$(RM) $(ROGUE52_OBJS)
	$(RM) $(ROGUE52_REDEF_EXPANDED)
	$(RM) $(ROGUE36_OBJS)
	$(RM) $(ROGUE36_REDEF_EXPANDED)
	$(RM) $(ROGUE36_REFSECTIONS)
	$(RM) $(SROGUE90_OBJS)
	$(RM) $(SROGUE90_REDEF_EXPANDED)
	$(RM) $(SROGUE90_REFSECTIONS)
	$(RM) core a.exe a.out a.exe.stackdump $(PROGRAM) $(PROGRAM).exe $(PROGRAM).lck
	$(RM) $(PROGRAM).tar $(PROGRAM).tar.gz $(PROGRAM).zip 
	$(RM) $(DISTNAME)/*
    
dist.src:
	$(MAKE) $(MAKEFILE) clean
	mkdir $(DISTNAME)
	cp $(CFILES) $(HDRS) $(MISC) $(AFILES) $(DISTNAME)
	tar cf $(DISTNAME)-src.tar $(DISTNAME)
	gzip -f $(DISTNAME)-src.tar
	rm -fr $(DISTNAME)

findpw: findpw.c xcrypt.o mdport.o xcrypt.o
	$(CC) -s -o findpw findpw.c xcrypt.o mdport.o -lcurses

scedit: scedit.o scmisc.o vers.o mdport.o xcrypt.o
	$(CC) -s -o scedit vers.o scedit.o scmisc.o mdport.o xcrypt.o -lcurses

scmisc.o scedit.o:
	$(CC) -O -c $(SF) $*.c

doc.nroff:
	tbl rogue.me | nroff -me | colcrt - > rogue.doc
	nroff -man rogue.6 | colcrt - > rogue.cat

doc.groff:
	groff -P-c -t -me -Tascii rogue.me | sed -e 's/.\x08//g' > rogue.doc
	groff -man rogue.6 | sed -e 's/.\x08//g' > rogue.cat

fixdocs:
	sed -e 's/@PROGRAM@/$(PROGRAM)/' -e 's/@SCOREFILE@/$(SCOREFILE)/' rogue.6.in > $(PROGRAM).6
	sed -e 's/@PROGRAM@/$(PROGRAM)/' -e 's/@SCOREFILE@/$(SCOREFILE)/' rogue.me.in > $(PROGRAM).me
	sed -e 's/@PROGRAM@/$(PROGRAM)/' -e 's/@SCOREFILE@/$(SCOREFILE)/' rogue.html.in > $(PROGRAM).html
	sed -e 's/@PROGRAM@/$(PROGRAM)/' -e 's/@SCOREFILE@/$(SCOREFILE)/' rogue.doc.in > $(PROGRAM).doc
	sed -e 's/@PROGRAM@/$(PROGRAM)/' -e 's/@SCOREFILE@/$(SCOREFILE)/' rogue.cat.in > $(PROGRAM).cat

dist.irix:
	$(MAKE) $(MAKEFILE) clean
	$(MAKE) $(MAKEFILE)  CC=cc $(PROGRAM)
	tar cf $(DISTNAME)-irix.tar $(PROGRAM) LICENSE.TXT $(DOCS)
	gzip -f $(DISTNAME)-irix.tar

dist.aix:
	$(MAKE) $(MAKEFILE) clean
	$(MAKE) $(MAKEFILE) CC=xlc CFLAGS="-qmaxmem=16768 -O3 -qstrict" $(PROGRAM)
	tar cf $(DISTNAME)-aix.tar $(PROGRAM) LICENSE.TXT $(DOCS)
	gzip -f $(DISTNAME)-aix.tar

dist.linux:
	$(MAKE) $(MAKEFILE) clean
	$(MAKE) $(MAKEFILE) $(PROGRAM)
	tar cf $(DISTNAME)-linux.tar $(PROGRAM) LICENSE.TXT $(DOCS)
	gzip -f $(DISTNAME)-linux.tar
	
dist.interix:
	@$(MAKE) $(MAKEFILE) clean
	@$(MAKE) $(MAKEFILE) CFLAGS="-ansi" $(PROGRAM)
	tar cf $(DISTNAME)-interix.tar $(PROGRAM) LICENSE.TXT $(DOCS)
	gzip -f $(DISTNAME)-interix.tar
	
dist.cygwin:
	@$(MAKE) $(MAKEFILE) --no-print-directory clean
	@$(MAKE) $(MAKEFILE) CPPFLAGS="-I/usr/include/ncurses" --no-print-directory $(PROGRAM)
	tar cf $(DISTNAME)-cygwin.tar $(PROGRAM).exe LICENSE.TXT $(DOCS)
	gzip -f $(DISTNAME)-cygwin.tar

#
# Use MINGW32-MAKE to build this target
#
dist.mingw32:
	@$(MAKE) $(MAKEFILE) --no-print-directory RM="cmd /c del" clean
	@$(MAKE) $(MAKEFILE) --no-print-directory CPPFLAGS="-I../pdcurses" LIBS="../pdcurses/pdcurses.a" $(PROGRAM)
	cmd /c del $(DISTNAME)-mingw32.zip
	zip $(DISTNAME)-mingw32.zip $(PROGRAM).exe LICENSE.TXT $(DOCS)
	
dist.djgpp:
	@$(MAKE) $(MAKEFILE) --no-print-directory clean
	@$(MAKE) $(MAKEFILE) --no-print-directory LDFLAGS="-L$(DJDIR)/LIB" \
	LIBS="-lpdcurses" $(PROGRAM)
	rm -f $(DISTNAME)-djgpp.zip
	zip $(DISTNAME)-djgpp.zip $(PROGRAM) LICENSE.TXT $(DOCS)

#
# Use NMAKE to build this targer
#

dist.win32:
	@$(MAKE) $(MAKEFILE) /NOLOGO O="obj" RM="-del" clean
	@$(MAKE) $(MAKEFILE) /NOLOGO O="obj" CC="CL" \
	    LIBS="..\pdcurses\pdcurses.lib shell32.lib user32.lib Advapi32.lib" \
	    EXE=".exe" OUTFLAG="/Fe" CPPFLAGS="-I..\pdcurses" \
	    CFLAGS="-nologo -Ox -wd4033 -wd4716" $(PROGRAM)
	-del $(DISTNAME)-win32.zip
	zip $(DISTNAME)-win32.zip $(PROGRAM).exe LICENSE.TXT $(DOCS)
