file(READ "${INPUT}" redef_text)
string(REPLACE "\r\n" "\n" redef_text "${redef_text}")
string(REPLACE "\r" "\n" redef_text "${redef_text}")
string(REPLACE "\n" ";" redef_lines "${redef_text}")

set(output_text "")
foreach(line IN LISTS redef_lines)
    string(STRIP "${line}" trimmed)
    if(trimmed STREQUAL "")
        continue()
    endif()

    string(APPEND output_text "${trimmed}\n")
    string(REGEX MATCH "^([^ \t]+)[ \t]+([^ \t]+)" match "${trimmed}")
    if(match)
        set(from "${CMAKE_MATCH_1}")
        set(to "${CMAKE_MATCH_2}")
        if(NOT from MATCHES "^\\.")
            string(APPEND output_text ".refptr.${from} ${PREFIX}_refptr_${from}\n")
        endif()
    endif()
endforeach()

get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT}" "${output_text}")
